### PR TITLE
fix: style download button on commits page

### PR DESCRIPTION
**Pull request by razak17**

### CODE REVIEW

**Comment by oe** [comment]
Thanks for you PR.

Could you add screenshots to describe what's changed, and add a link can test the changes? I did not see any difference😅

**Comment by razak17** [comment]
### The download button is not styled properly on the commits page as shown below:

Before:

Screenshot 2022-10-14 at 16-05-44 Commits · razak17_nvim

After:

Screenshot 2022-10-14 at 16-06-14 Commits · razak17_nvim

**Comment by oe** [comment]
Actually I think the download button on commits list page should be removed, it makes no sense.

**Comment by razak17** [comment]
Yep. I also thought about but then I was able to style it pretty easily.

**Comment by oe** [comment]
I've just fixed this issue, you can update to the latest version and have a try

* [install script via greasyfork](https://greasyfork.org/scripts/411834-download-github-repo-sub-folder/code/Download%20github%20repo%20sub-folder.user.js), [greasyfork home page](https://greasyfork.org/scripts/411834-download-github-repo-sub-folder)
* [install script via openuserjs](https://openuserjs.org/install/oe/Download_github_repo_online.user.js), [openuserjs home page](https://openuserjs.org/scripts/oe/Download_github_repo_online)

**Pull request closed without merging**
